name: Zig Test and Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ZIG_VERSION: 0.13.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Unit testing
        run: zig build test --summary all

      - name: Run benchmarks
        run: zig build bench -Doptimize=ReleaseFast

      - name: Run node
        run: |
          zig build -Doptimize=Debug run -- node &
          BITCOIN_NODE_PID=$!
          sleep 1
          kill $BITCOIN_NODE_PID
